// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyasrqfmrjbhclhiihfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5YXNycWZtcmpiaGNsaGlpaGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjM4NDYsImV4cCI6MjA1OTgzOTg0Nn0.aFCx2HSRZ9DsAIuznT0YIUGx7sXbvuEFD69TVrKHQAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);